### ISSUE TITLE
mask error in transaction details

### ISSUE THREAD

**Issue by aminNazarii** [ZarinPal/Panel#303]
@MA7 check this 
Error in render function: "TypeError: Cannot read property 'mask' of null"
<img width="1440" alt="screen shot 2017-11-08 at 10 35 21 am" src="https://user-images.githubusercontent.com/19771561/32535758-af2fde1a-c470-11e7-9cc8-7b25c6976919.png">

**Comment by MA7** [comment]
ino to kodom page gerefti ? @aminNazarii
