### ISSUE TITLE
how i can help to develop Zarinpal PAnel ?

### ISSUE THREAD

**Issue by vahidalvandi** [ZarinPal/Panel#606]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by amiri27** [comment]
Dear Vahid,

Thanks for your contribution on our project, ZarinPal Panel hosted on [my.zarinpal.com](https://my.zarinpal.com). We wrapped everything which is needed to run on development machine so you can simply take a clone of project and continue to develop or fix some missed bugs by sending PR to this project..

If you are interested to join our team just simply send us your CV to jobs [at] ZarinPal [dot] com..

Regards,

**Comment by vahidalvandi** [comment]
i saw panel design technical , awesome for vue , pug , webpack and any this is update !

i funder webine.ir and work same frameworks . how i can join your team ?

**Comment by amiri27** [comment]
Dear @vahidalvandi

For sure.. We look for talents who care about the quality.. Just send us your CV and our HR team will set a meeting for that..

Regards,
